from buratino.models.contracts import VerificationReport


def test_verification_report_contract_stable_keys() -> None:
    report = VerificationReport(
        event_id=1,
        event_name="event",
        event_type="qualitative",
        event_fact_status="не подтверждено",
        phr_fact_status="не указано",
        event_primary_file=None,
        phr_primary_file=None,
        logic_is_valid=True,
        primary_model="primary",
        audit_model="audit",
        event_reasoning="none",
        phr_reasoning="none",
    )

    assert set(report.to_dict()) == {
        "event_id",
        "event_name",
        "event_type",
        "event_fact_status",
        "phr_fact_status",
        "event_primary_file",
        "phr_primary_file",
        "logic_is_valid",
        "primary_model",
        "audit_model",
        "event_reasoning",
        "phr_reasoning",
        "event_diagnostic_reasoning",
        "phr_diagnostic_reasoning",
        "diagnostic_stage",
        "diagnostic_reason",
        "evidence_source_used",
        "ocr_available",
        "summary_available",
        "ranking_selected_files",
        "analyzed_files",
        "doc_level_confirmed_files",
        "docs_rejected_by_empty_evidence",
        "docs_rejected_by_relation",
        "docs_rejected_by_date",
        "audit_changed_decision",
        "missing_requirements_human",
        "best_candidate_file",
        "best_candidate_reason",
        "error_stage",
        "error_type",
        "raw_response_preview",
        "model_name",
        "prompt_name",
        "total_docs",
        "ranking_enabled",
        "ranking_limit",
        "ranking_selected_doc_ids",
        "ranking_selected_file_names",
        "ranking_rejected_file_names",
        "ocr_chunks_analyzed",
        "event_deadline_status",
        "event_deadline_reason",
        "event_deadline_date",
        "event_deadline_source_file",
        "event_deadline_source",
        "event_deadline_raw_text",
        "implementation_deadline_raw",
        "implementation_deadline_normalized",
        "date_checked_files",
        "date_missing_files",
        "date_late_files",
        "date_on_time_files",
        "supporting_files_date_status",
        "detected_errors",
        "event_documents",
        "phr_documents",
        "supporting_files",
        "audit_reasoning",
        "primary_logic_is_valid",
        "primary_audit_reasoning",
        "audit_rerun_performed",
        "audit_rerun_event_documents",
        "audit_rerun_phr_documents",
        "audit_rerun_event_status",
        "audit_rerun_phr_status",
        "audit_rerun_logic_is_valid",
        "audit_rerun_reasoning",
        "confirming_documents_relation",
        "evidence_trace",
    }
